== Cascade
Cascade is a library containing methods to allow http://en.wikipedia.org/wiki/Method_chaining[method chaining] in .NET code. The target is to allow .NET developers method chaining almost everywhere inside code. To achieve this Cascade make usage of http://msdn.microsoft.com/en-us/library/bb383977.aspx[extension methods].
To make Cascade most versatile and usable in most projects, it waives dependencies. At the moment only a reference on the _System_ namespace (mscorlib.dll) which is referenced by any .NET project anyway.

*Who?* Cascade is a library for .NET developers and can be used in almost every code base. You will not be able to create fancy UI's nor you get an er-mapper. It's just extension methods for method chaining. +
*Why?* To be honest, Cascade is optional in any way and aspect. However, you can write code that may be easier to read for you than without Cascade. +
*How?* You can easily use Cascade by using the http://nuget.org/packages/Cascade[NuGet]. After adding the package to your project you can access the extension methods by adding the +using Cascade;+ statement at top of your code file. +
*Now?* After adding the package to your project and adding the +using Cascade;+ to your code files, you can start with Cascade. You can try the +IfNotNull+ and +IfNull+ extension to create something fancy like +myObject.IfNotNull(t => Console.WriteLine(t));+

If you want to explore more of Cascade you can visit the https://github.com/jbuechner/cascade/wiki[wiki].

== License
Cascade is licensed under the https://github.com/jbuechner/cascade/wiki/License[Apache License 2.0]. Feel free to distribute and modify sources and binaries.